### ISSUE TITLE
Viacom?

### ISSUE THREAD

**Issue by AlJohri** [mludowise/AppleTV-XFinity-Activation#2]
do you have any details as to why it doesn't work with Viacom owned networks? or why the option doesn't exist in the first place to activate normally?

**Comment by mludowise** [comment]
Sorry for not responding sooner, I was having some GH notification issues that have now been remedied.

### Why doesn't the option exist to activate normally with Xfinity?
I don't know why the option doesn't currently exist to authenticate with Xfinity on Viacom or any other app that they don't support. I can only speculate that it's because it has to do with streaming rights.

### Do you have any details as to why activating with Xfinity doesn't work with Viacom owned networks?

The Viacom AppleTV apps (MTV, Comedy Central, Nickelodeon, etc) have a different way of authenticating than the other apps. These apps ask for you to select your TV provider before they display an authentication code and they don't provide Comcast Xfinity as an option:
![image](https://cloud.githubusercontent.com/assets/1626168/23088511/f7eab1c0-f531-11e6-81a4-0d89a16d7122.png)

When the app requests an activation code from their server, it registers which authentication service (AT&T, DIRECTV, etc) you selected. When you go to their activation URL and enter the authentication code, they lookup what provider you originally selected and only accept the selected provider as a valid authentication. Because Xfinity is never an option to select in the app, the app cannot register Xfinity as a valid authentication mechanism, and will not complete the log-in process when you attempt to authenticate with Xfinity.

The other streaming apps which I do support are not as sophisticated and don't register which authentication service you're using before they generate a code. Once a code is generated, they will accept any authentication service accepted by Adobe's authentication API, including Xfinity.

The only way that the Viacom apps could allow Xfinity authentication would be if Xfinity was an available option prior to generating a code. I don't believe there is any way to "trick" the apps into using Xfinity authentication.
